apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/vadym-dubykhvist/nest-js-api-practice
      targetRevision: main
      path: chart
      helm:
        valueFiles:
          - $values/environments/dev/values.yaml

    - repoURL: https://github.com/vadym-dubykhvist/nest-js-api-practice-deploy
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
